#
# .gitlab-ci.yml
#

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$(basename $(pwd))"

arch-docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build --pull -t "$DOCKER_IMAGE" arch/Dockerfile .
    - docker push "$DOCKER_IMAGE"

fedora-docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:latest"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build --pull -t "$DOCKER_IMAGE" -f fedora/Dockerfile .
    - docker push "$DOCKER_IMAGE"
